# Generated by Django 3.2.5 on 2021-08-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awcapp', '0002_auto_20210808_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='awcentry',
            name='supporter_aadhar',
            field=models.IntegerField(default=20, verbose_name='Supporter Aadhar No'),
        ),
        migrations.AddField(
            model_name='awcentry',
            name='worker_aadhar',
            field=models.IntegerField(default=20, verbose_name='Worker Aadhar No'),
        ),
        migrations.AlterField(
            model_name='awcentry',
            name='supporter_mobile_no',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Supporter Mobile No'),
        ),
        migrations.AlterField(
            model_name='awcentry',
            name='supporter_name',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Supporter Name'),
        ),
    ]
