# Generated by Django 3.2.5 on 2021-08-11 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awcapp', '0003_auto_20210810_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostpartumMother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awc_center_name', models.CharField(blank=True, max_length=180, null=True, verbose_name='Awc Center Name')),
                ('name', models.CharField(blank=True, max_length=180, null=True, verbose_name='Gravid Women Name')),
                ('aadhar', models.CharField(blank=True, max_length=180, null=True, verbose_name='Gravid Women Aadhar')),
                ('husband_name', models.CharField(blank=True, max_length=180, null=True, verbose_name='Husband Name')),
                ('delivery_date', models.DateField(blank=True, max_length=8, null=True, verbose_name='Probable Delivery Date')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='awcapp.sector')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='childinfo',
            name='amusc',
        ),
        migrations.RemoveField(
            model_name='childinfo',
            name='children_age',
        ),
        migrations.RemoveField(
            model_name='childinfo',
            name='height',
        ),
        migrations.RemoveField(
            model_name='childinfo',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='childinfo',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='gravidwomeninfo',
            name='awc_name',
        ),
        migrations.AddField(
            model_name='childinfo',
            name='cast',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='childinfo',
            name='fathers_aadhar',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name="Father's Aadhar"),
        ),
        migrations.AddField(
            model_name='childinfo',
            name='is_handicapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='childinfo',
            name='mothers_aadhar',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name="Mother's Aadhar"),
        ),
        migrations.AddField(
            model_name='gravidwomeninfo',
            name='awc_center_name',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Awc Center Name'),
        ),
        migrations.AddField(
            model_name='gravidwomeninfo',
            name='gravid_women_aadhar',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Gravid Women Aadhar'),
        ),
        migrations.AddField(
            model_name='gravidwomeninfo',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='teenagegirl',
            name='dob',
            field=models.DateField(blank=True, max_length=8, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='teenagegirl',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name="Father's Name"),
        ),
        migrations.AddField(
            model_name='teenagegirl',
            name='girl_aadhar',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Teen Age Girl Aadhar'),
        ),
        migrations.CreateModel(
            name='TeenAgeGirlStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(blank=True, max_length=180, null=True)),
                ('hemoglobin_level', models.CharField(blank=True, max_length=180, null=True)),
                ('plasmodium_inf_test', models.BooleanField(default=False)),
                ('nutritious_food', models.BooleanField(default=False)),
                ('ifa_tablet', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('girl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='awcapp.teenagegirl')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superviser_name', models.CharField(blank=True, max_length=180, null=True, verbose_name='Project Name')),
                ('project_name', models.CharField(blank=True, max_length=180, null=True, verbose_name='Project Name')),
                ('awc_center_name', models.CharField(blank=True, max_length=180, null=True, verbose_name='Awc Center name')),
                ('awc_center_code', models.IntegerField(default=20, verbose_name='Awc Center Code')),
                ('village_council', models.CharField(blank=True, max_length=180, null=True, verbose_name='Village Council')),
                ('village', models.CharField(blank=True, max_length=180, null=True, verbose_name='Village')),
                ('worker_name', models.CharField(blank=True, max_length=180, null=True, verbose_name='Worker Name')),
                ('worker_aadhar', models.IntegerField(default=20, verbose_name='Worker Aadhar No')),
                ('worker_mobile_no', models.CharField(blank=True, max_length=180, null=True, verbose_name='Worker Name')),
                ('supporter_name', models.CharField(blank=True, max_length=180, null=True, verbose_name='Supporter Name')),
                ('supporter_aadhar', models.IntegerField(default=20, verbose_name='Supporter Aadhar No')),
                ('supporter_mobile_no', models.CharField(blank=True, max_length=180, null=True, verbose_name='Supporter Mobile No')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='awcapp.sector')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostpartumStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemoglobin_level', models.CharField(blank=True, max_length=180, null=True)),
                ('anc_checkup', models.BooleanField(default=False)),
                ('plasmodium_inf_test', models.BooleanField(default=False)),
                ('nutritious_food', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('postpartum_mother', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='awcapp.postpartummother')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GravidWomenStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(blank=True, max_length=180, null=True)),
                ('probable_delivery_date', models.DateField(blank=True, max_length=8, null=True, verbose_name='Probable Delivery Date')),
                ('hemoglobin_level', models.CharField(blank=True, max_length=180, null=True)),
                ('weight', models.CharField(blank=True, max_length=180, null=True)),
                ('anc_checkup', models.BooleanField(default=False)),
                ('ifa_tablet', models.BooleanField(default=False)),
                ('nutritious_food', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('gravid_women', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='awcapp.gravidwomeninfo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeathInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awc_center_name', models.CharField(blank=True, max_length=180, null=True, verbose_name='Awc Center Name')),
                ('benificiary_name', models.CharField(blank=True, max_length=180, null=True, verbose_name='Benificiary Name')),
                ('day_of_death', models.DateField(blank=True, max_length=8, null=True, verbose_name='Day of Death')),
                ('death_reason', models.CharField(blank=True, max_length=180, null=True, verbose_name='Death Reason')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChildStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(blank=True, max_length=180, null=True, verbose_name='Weight')),
                ('height', models.CharField(blank=True, max_length=180, null=True, verbose_name='Height')),
                ('amusc', models.CharField(blank=True, max_length=180, null=True, verbose_name='Amusc')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('child_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='awcapp.childinfo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
