# Generated by Django 3.2.5 on 2021-08-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awcapp', '0006_auto_20210812_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpartummother',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
