# Generated by Django 3.2.5 on 2021-08-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awcapp', '0007_postpartummother_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='teenagegirl',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
