# Generated by Django 3.2.5 on 2021-09-06 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awcapp', '0009_user_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='awcentry',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='awcapp.district'),
        ),
        migrations.AlterField(
            model_name='childstatus',
            name='child_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_status', to='awcapp.childinfo'),
        ),
        migrations.AlterField(
            model_name='gravidwomenstatus',
            name='gravid_women',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gravid_women_status', to='awcapp.gravidwomeninfo'),
        ),
        migrations.AlterField(
            model_name='postpartumstatus',
            name='postpartum_mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postpartum_mother_status', to='awcapp.postpartummother'),
        ),
        migrations.AlterField(
            model_name='teenagegirlstatus',
            name='girl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teenage_girl_status', to='awcapp.teenagegirl'),
        ),
    ]
