# Generated by Django 3.2.5 on 2021-09-06 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awcapp', '0010_auto_20210906_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awcentry',
            name='district',
        ),
        migrations.AddField(
            model_name='childinfo',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='awcapp.district'),
        ),
    ]
